<?php

namespace App\Services;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class SeederService
{
    public static function getPrefixSeeders($buildingID): array
    {
        return [
            [
                'type' => 'QUOTATION',
                'full_name' => 'Quotation',
                'prefix' => 'QUOT',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'HR',
                'full_name' => 'Human Resource',
                'prefix' => 'HR',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'TRANSFER',
                'full_name' => 'Title Transfer',
                'prefix' => 'TRANSFER',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'INSTALLMENT',
                'full_name' => 'Installment',
                'prefix' => 'INST',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Purchase',
                'full_name' => 'Purchase',
                'prefix' => 'PUR',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'INV',
                'full_name' => 'Sales Invoice',
                'prefix' => 'INV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Income',
                'full_name' => 'Income',
                'prefix' => 'INC',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Bank Transaction',
                'full_name' => 'Bank Transaction',
                'prefix' => 'BT',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Expense',
                'full_name' => 'Expense Voucher',
                'prefix' => 'EXP',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'INVT',
                'full_name' => 'Inventory Voucher',
                'prefix' => 'INVT',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Advance',
                'full_name' => 'Advance Payment Voucher',
                'prefix' => 'APV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'PR Balance',
                'full_name' => 'Previous Balance Voucher',
                'prefix' => 'PBV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Opening',
                'full_name' => 'Opening Balance Voucher',
                'prefix' => 'OBV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'PM',
                'full_name' => 'Seller Payment Voucher',
                'prefix' => 'SPV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'CR',
                'full_name' => 'Customer Receive Voucher',
                'prefix' => 'CRV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Broker Payment',
                'full_name' => 'Broker Payment Voucher',
                'prefix' => 'BRPM',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'AD',
                'full_name' => 'Cash Adjustment Voucher',
                'prefix' => 'CAV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'DV',
                'full_name' => 'Debit Voucher',
                'prefix' => 'DV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'CV',
                'full_name' => 'Credit Voucher',
                'prefix' => 'CV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Contra',
                'full_name' => 'Contra Voucher',
                'prefix' => 'CONTRA',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'JV',
                'full_name' => 'Journal Voucher',
                'prefix' => 'JV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Salary',
                'full_name' => 'Salary Voucher',
                'prefix' => 'SV',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
            [
                'type' => 'Loan',
                'full_name' => 'Loan Request',
                'prefix' => 'LR',
                'number' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'building_id' => $buildingID,
            ],
        ];
    }

    public static function runSeeder($seederData, $table)
    {
        return DB::table($table)->insert($seederData);
    }
}
