<?php

namespace Database\Seeders\RealEstate;

use App\Enum\TableEnum;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table(TableEnum::COUNTRIES)->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table(TableEnum::COUNTRIES)->insert(['id' =>
            ['id' => 1, 'name' => 'Afghanistan'],
            ['id' => 2, 'name' => 'Albania'],
            ['id' => 3, 'name' => 'Algeria'],
            ['id' => 4, 'name' => 'American Samoa'],
            ['id' => 5, 'name' => 'Andorra'],
            ['id' => 6, 'name' => 'Angola'],
            ['id' => 7, 'name' => 'Anguilla'],
            ['id' => 8, 'name' => 'Antarctica'],
            ['id' => 9, 'name' => 'Antigua and Barbuda'],
            ['id' => 10, 'name' => 'Argentina'],
            ['id' => 11, 'name' => 'Armenia'],
            ['id' => 12, 'name' => 'Aruba'],
            ['id' => 13, 'name' => 'Australia'],
            ['id' => 14, 'name' => 'Austria'],
            ['id' => 15, 'name' => 'Azerbaijan'],
            ['id' => 16, 'name' => 'Bahamas'],
            ['id' => 17, 'name' => 'Bahrain'],
            ['id' => 18, 'name' => 'Bangladesh'],
            ['id' => 19, 'name' => 'Barbados'],
            ['id' => 20, 'name' => 'Belarus'],
            ['id' => 21, 'name' => 'Belgium'],
            ['id' => 22, 'name' => 'Belize'],
            ['id' => 23, 'name' => 'Benin'],
            ['id' => 24, 'name' => 'Bermuda'],
            ['id' => 25, 'name' => 'Bhutan'],
            ['id' => 26, 'name' => 'Bolivia'],
            ['id' => 27, 'name' => 'Bosnia and Herzegovina'],
            ['id' => 28, 'name' => 'Botswana'],
            ['id' => 29, 'name' => 'Bouvet Island'],
            ['id' => 30, 'name' => 'Brazil'],
            ['id' => 31, 'name' => 'British Indian Ocean Territory'],
            ['id' => 32, 'name' => 'Brunei Darussalam'],
            ['id' => 33, 'name' => 'Bulgaria'],
            ['id' => 34, 'name' => 'Burkina Faso'],
            ['id' => 35, 'name' => 'Burundi'],
            ['id' => 36, 'name' => 'Cambodia'],
            ['id' => 37, 'name' => 'Cameroon'],
            ['id' => 38, 'name' => 'Canada'],
            ['id' => 39, 'name' => 'Cape Verde'],
            ['id' => 40, 'name' => 'Cayman Islands'],
            ['id' => 41, 'name' => 'Central African Republic'],
            ['id' => 42, 'name' => 'Chad'],
            ['id' => 43, 'name' => 'Chile'],
            ['id' => 44, 'name' => 'China'],
            ['id' => 45, 'name' => 'Christmas Island'],
            ['id' => 46, 'name' => 'Cocos (Keeling) Islands'],
            ['id' => 47, 'name' => 'Colombia'],
            ['id' => 48, 'name' => 'Comoros'],
            ['id' => 49, 'name' => 'Congo'],
            ['id' => 50, 'name' => 'Congo, the Democratic Republic of the'],
            ['id' => 51, 'name' => 'Cook Islands'],
            ['id' => 52, 'name' => 'Costa Rica'],
            ['id' => 53, 'name' => 'Cote D\'Ivoire'],
            ['id' => 54, 'name' => 'Croatia'],
            ['id' => 55, 'name' => 'Cuba'],
            ['id' => 56, 'name' => 'Cyprus'],
            ['id' => 57, 'name' => 'Czech Republic'],
            ['id' => 58, 'name' => 'Denmark'],
            ['id' => 59, 'name' => 'Djibouti'],
            ['id' => 60, 'name' => 'Dominica'],
            ['id' => 61, 'name' => 'Dominican Republic'],
            ['id' => 62, 'name' => 'Ecuador'],
            ['id' => 63, 'name' => 'Egypt'],
            ['id' => 64, 'name' => 'El Salvador'],
            ['id' => 65, 'name' => 'Equatorial Guinea'],
            ['id' => 66, 'name' => 'Eritrea'],
            ['id' => 67, 'name' => 'Estonia'],
            ['id' => 68, 'name' => 'Ethiopia'],
            ['id' => 69, 'name' => 'Falkland Islands (Malvinas)'],
            ['id' => 70, 'name' => 'Faroe Islands'],
            ['id' => 71, 'name' => 'Fiji'],
            ['id' => 72, 'name' => 'Finland'],
            ['id' => 73, 'name' => 'France'],
            ['id' => 74, 'name' => 'French Guiana'],
            ['id' => 75, 'name' => 'French Polynesia'],
            ['id' => 76, 'name' => 'French Southern Territories'],
            ['id' => 77, 'name' => 'Gabon'],
            ['id' => 78, 'name' => 'Gambia'],
            ['id' => 79, 'name' => 'Georgia'],
            ['id' => 80, 'name' => 'Germany'],
            ['id' => 81, 'name' => 'Ghana'],
            ['id' => 82, 'name' => 'Gibraltar'],
            ['id' => 83, 'name' => 'Greece'],
            ['id' => 84, 'name' => 'Greenland'],
            ['id' => 85, 'name' => 'Grenada'],
            ['id' => 86, 'name' => 'Guadeloupe'],
            ['id' => 87, 'name' => 'Guam'],
            ['id' => 88, 'name' => 'Guatemala'],
            ['id' => 89, 'name' => 'Guyana'],
            ['id' => 90, 'name' => 'Guinea-Bissau'],
            ['id' => 91, 'name' => 'Haiti'],
            ['id' => 92, 'name' => 'Heard Island and Mcdonald Islands'],
            ['id' => 93, 'name' => 'Holy See (Vatican City State)'],
            ['id' => 94, 'name' => 'Honduras'],
            ['id' => 95, 'name' => 'Hong Kong'],
            ['id' => 96, 'name' => 'Hungary'],
            ['id' => 97, 'name' => 'Iceland'],
            ['id' => 98, 'name' => 'India'],
            ['id' => 99, 'name' => 'Indonesia'],
            ['id' => 100, 'name' => 'Iran'],
            ['id' => 101, 'name' => 'Iraq'],
            ['id' => 102, 'name' => 'Ireland'],
            ['id' => 103, 'name' => 'Israel'],
            ['id' => 104, 'name' => 'Italy'],
            ['id' => 105, 'name' => 'Jamaica'],
            ['id' => 106, 'name' => 'Japan'],
            ['id' => 107, 'name' => 'Jordan'],
            ['id' => 108, 'name' => 'Kazakhstan'],
            ['id' => 109, 'name' => 'Kenya'],
            ['id' => 110, 'name' => 'Kiribati'],
            ['id' => 111, 'name' => 'South Korea'],
            ['id' => 112, 'name' => 'North Korea'],
            ['id' => 113, 'name' => 'Kuwait'],
            ['id' => 114, 'name' => 'Kyrgyzstan'],
            ['id' => 115, 'name' => 'Lao People\'s Democratic Republic'],
            ['id' => 116, 'name' => 'Latvia'],
            ['id' => 117, 'name' => 'Lebanon'],
            ['id' => 118, 'name' => 'Lesotho'],
            ['id' => 119, 'name' => 'Liberia'],
            ['id' => 120, 'name' => 'Libyan Arab Jamahiriya'],
            ['id' => 121, 'name' => 'Liechtenstein'],
            ['id' => 122, 'name' => 'Lithuania'],
            ['id' => 123, 'name' => 'Luxembourg'],
            ['id' => 124, 'name' => 'Macao'],
            ['id' => 125, 'name' => 'Macedonia'],
            ['id' => 126, 'name' => 'Madagascar'],
            ['id' => 127, 'name' => 'Malawi'],
            ['id' => 128, 'name' => 'Malaysia'],
            ['id' => 129, 'name' => 'Maldives'],
            ['id' => 130, 'name' => 'Mali'],
            ['id' => 131, 'name' => 'Malta'],
            ['id' => 132, 'name' => 'Marshall Islands'],
            ['id' => 133, 'name' => 'Martinique'],
            ['id' => 134, 'name' => 'Mauritania'],
            ['id' => 135, 'name' => 'Mauritius'],
            ['id' => 136, 'name' => 'Mayotte'],
            ['id' => 137, 'name' => 'Mexico'],
            ['id' => 138, 'name' => 'Micronesia'],
            ['id' => 139, 'name' => 'Moldova'],
            ['id' => 140, 'name' => 'Monaco'],
            ['id' => 141, 'name' => 'Mongolia'],
            ['id' => 142, 'name' => 'Montserrat'],
            ['id' => 143, 'name' => 'Morocco'],
            ['id' => 144, 'name' => 'Mozambique'],
            ['id' => 145, 'name' => 'Myanmar'],
            ['id' => 146, 'name' => 'Namibia'],
            ['id' => 147, 'name' => 'Nauru'],
            ['id' => 148, 'name' => 'Nepal'],
            ['id' => 149, 'name' => 'Netherlands'],
            ['id' => 150, 'name' => 'Netherlands Antilles'],
            ['id' => 151, 'name' => 'New Caledonia'],
            ['id' => 152, 'name' => 'New Zealand'],
            ['id' => 153, 'name' => 'Nicaragua'],
            ['id' => 154, 'name' => 'Niger'],
            ['id' => 155, 'name' => 'Nigeria'],
            ['id' => 156, 'name' => 'Niue'],
            ['id' => 157, 'name' => 'Norfolk Island'],
            ['id' => 158, 'name' => 'Northern Mariana Islands'],
            ['id' => 159, 'name' => 'Norway'],
            ['id' => 160, 'name' => 'Oman'],
            ['id' => 161, 'name' => 'Pakistan'],
            ['id' => 162, 'name' => 'Palau'],
            ['id' => 163, 'name' => 'Palestinian Territory, Occupied'],
            ['id' => 164, 'name' => 'Panama'],
            ['id' => 165, 'name' => 'Papua New Guinea'],
            ['id' => 166, 'name' => 'Paraguay'],
            ['id' => 167, 'name' => 'Peru'],
            ['id' => 168, 'name' => 'Philippines'],
            ['id' => 169, 'name' => 'Pitcairn'],
            ['id' => 170, 'name' => 'Poland'],
            ['id' => 171, 'name' => 'Portugal'],
            ['id' => 172, 'name' => 'Puerto Rico'],
            ['id' => 173, 'name' => 'Qatar'],
            ['id' => 174, 'name' => 'Reunion'],
            ['id' => 175, 'name' => 'Romania'],
            ['id' => 176, 'name' => 'Russian Federation'],
            ['id' => 177, 'name' => 'Rwanda'],
            ['id' => 178, 'name' => 'Saint Helena'],
            ['id' => 179, 'name' => 'Saint Kitts and Nevis'],
            ['id' => 180, 'name' => 'Saint Lucia'],
            ['id' => 181, 'name' => 'Saint Pierre and Miquelon'],
            ['id' => 182, 'name' => 'Saint Vincent and the Grenadines'],
            ['id' => 183, 'name' => 'Samoa'],
            ['id' => 184, 'name' => 'San Marino'],
            ['id' => 185, 'name' => 'Sao Tome and Principe'],
            ['id' => 186, 'name' => 'Saudi Arabia'],
            ['id' => 187, 'name' => 'Senegal'],
            ['id' => 188, 'name' => 'Serbia and Montenegro'],
            ['id' => 189, 'name' => 'Seychelles'],
            ['id' => 190, 'name' => 'Sierra Leone'],
            ['id' => 191, 'name' => 'Singapore'],
            ['id' => 192, 'name' => 'Slovakia'],
            ['id' => 193, 'name' => 'Slovenia'],
            ['id' => 194, 'name' => 'Solomon Islands'],
            ['id' => 195, 'name' => 'Somalia'],
            ['id' => 196, 'name' => 'South Africa'],
            ['id' => 197, 'name' => 'South Georgia and the South Sandwich Islands'],
            ['id' => 198, 'name' => 'Spain'],
            ['id' => 199, 'name' => 'Sri Lanka'],
            ['id' => 200, 'name' => 'Sudan'],
            ['id' => 201, 'name' => 'Suriname'],
            ['id' => 202, 'name' => 'Svalbard and Jan Mayen'],
            ['id' => 203, 'name' => 'Swaziland'],
            ['id' => 204, 'name' => 'Sweden'],
            ['id' => 205, 'name' => 'Switzerland'],
            ['id' => 206, 'name' => 'Syrian Arab Republic'],
            ['id' => 207, 'name' => 'Taiwan, Province of China'],
            ['id' => 208, 'name' => 'Tajikistan'],
            ['id' => 209, 'name' => 'Tanzania, United Republic of'],
            ['id' => 210, 'name' => 'Thailand'],
            ['id' => 211, 'name' => 'Timor-Leste'],
            ['id' => 212, 'name' => 'Togo'],
            ['id' => 213, 'name' => 'Tokelau'],
            ['id' => 214, 'name' => 'Tonga'],
            ['id' => 215, 'name' => 'Trinidad and Tobago'],
            ['id' => 216, 'name' => 'Tunisia'],
            ['id' => 217, 'name' => 'Turkey'],
            ['id' => 218, 'name' => 'Turkmenistan'],
            ['id' => 219, 'name' => 'Turks and Caicos Islands'],
            ['id' => 220, 'name' => 'Tuvalu'],
            ['id' => 221, 'name' => 'Uganda'],
            ['id' => 222, 'name' => 'Ukraine'],
            ['id' => 223, 'name' => 'United Arab Emirates'],
            ['id' => 224, 'name' => 'United Kingdom'],
            ['id' => 225, 'name' => 'United States'],
            ['id' => 226, 'name' => 'United States Minor Outlying Islands'],
            ['id' => 227, 'name' => 'Uruguay'],
            ['id' => 228, 'name' => 'Uzbekistan'],
            ['id' => 229, 'name' => 'Vanuatu'],
            ['id' => 230, 'name' => 'Venezuela'],
            ['id' => 231, 'name' => 'Vietnam'],
            ['id' => 232, 'name' => 'Virgin Islands, British'],
            ['id' => 233, 'name' => 'Virgin Islands, U.s.'],
            ['id' => 234, 'name' => 'Wallis and Futuna'],
            ['id' => 235, 'name' => 'Western Sahara'],
            ['id' => 236, 'name' => 'Yemen'],
            ['id' => 237, 'name' => 'Zambia'],
            ['id' => 238, 'name' => 'Zimbabwe'],
        ]);
    }
}
