<?php

namespace Database\Seeders\Accounts;

use App\Enum\TableEnum;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountHeadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table(TableEnum::ACCOUNT_HEADS)->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table(TableEnum::ACCOUNT_HEADS)->insert([
            [
                'HeadCode' => '50202',
                'HeadName' => 'Account Payable',
                'PHeadName' => 'Current Liabilities',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00'
            ],
            [
                'HeadCode' => '10203',
                'HeadName' => 'Account Receivable',
                'PHeadName' => 'Current Asset',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '1',
                'HeadName' => 'Assets',
                'PHeadName' => 'COA',
                'HeadLevel' => 0, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '10201',
                'HeadName' => 'Cash & Cash Equivalent',
                'PHeadName' => 'Current Asset',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '1020102',
                'HeadName' => 'Cash At Bank',
                'PHeadName' => 'Cash & Cash Equivalent',
                'HeadLevel' => 3, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '1020101',
                'HeadName' => 'Cash In Hand',
                'PHeadName' => 'Cash & Cash Equivalent',
                'HeadLevel' => 3, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '102',
                'HeadName' => 'Current Asset',
                'PHeadName' => 'Assets',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '502',
                'HeadName' => 'Current Liabilities',
                'PHeadName' => 'Liabilities',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '1020301',
                'HeadName' => 'Customer Receivable',
                'PHeadName' => 'Account Receivable',
                'HeadLevel' => 3, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '401',
                'HeadName' => 'Default expense',
                'PHeadName' => 'Expense',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'E',
                'IsBudget' => 1,
                'IsDepreciation' => 1,
                'DepreciationRate' => '1.00',
            ],
            [
                'HeadCode' => '50204',
                'HeadName' => 'Employee Ledger',
                'PHeadName' => 'Current Liabilities',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '403',
                'HeadName' => 'Employee Salary',
                'PHeadName' => 'Expense',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'E',
                'IsBudget' => 0,
                'IsDepreciation' => 1,
                'DepreciationRate' => '1.00',
            ],
            [
                'HeadCode' => '2',
                'HeadName' => 'Equity',
                'PHeadName' => 'COA',
                'HeadLevel' => 0, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '4',
                'HeadName' => 'Expense',
                'PHeadName' => 'COA',
                'HeadLevel' => 0, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'E',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '3',
                'HeadName' => 'Income',
                'PHeadName' => 'COA',
                'HeadLevel' => 0, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'I',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '10107',
                'HeadName' => 'Inventory',
                'PHeadName' => 'Current Asset',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '5',
                'HeadName' => 'Liabilities',
                'PHeadName' => 'COA',
                'HeadLevel' => 0, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '1020302',
                'HeadName' => 'Loan Receivable',
                'PHeadName' => 'Account Receivable',
                'HeadLevel' => 3, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '101',
                'HeadName' => 'Non Current Assets',
                'PHeadName' => 'Assets',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '501',
                'HeadName' => 'Non Current Liabilities',
                'PHeadName' => 'Liabilities',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '402',
                'HeadName' => 'Flat Purchase',
                'PHeadName' => 'Expense',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'E',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '303',
                'HeadName' => 'Product Sale',
                'PHeadName' => 'Income',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'I',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '304',
                'HeadName' => 'Service Income',
                'PHeadName' => 'Income',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'I',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '10108',
                'HeadName' => 'Service Receive',
                'PHeadName' => 'Non Current Assets',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 1,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '50203',
                'HeadName' => 'Tax',
                'PHeadName' => 'Current Liabilities',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 0,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '400',
                'HeadName' => 'Brokery Payment',
                'PHeadName' => 'Expense',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'E',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '50205',
                'HeadName' => 'Brokery Payable',
                'PHeadName' => 'Current Liabilities',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 0, 'IsGL' => 1,
                'HeadType' => 'L',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '312',
                'HeadName' => 'Brokery Income',
                'PHeadName' => 'Income',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'I',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '313',
                'HeadName' => 'Title Transfer Fee',
                'PHeadName' => 'Income',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'I',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '314',
                'HeadName' => 'Installment Penalty Income',
                'PHeadName' => 'Income',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'I',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '315',
                'HeadName' => 'Commodity Profit',
                'PHeadName' => 'Income',
                'HeadLevel' => 1, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 0,
                'HeadType' => 'I',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
            [
                'HeadCode' => '10101',
                'HeadName' => 'Commodity',
                'PHeadName' => 'Non Current Assets',
                'HeadLevel' => 2, 'IsActive' => 1,
                'IsTransaction' => 1, 'IsGL' => 1,
                'HeadType' => 'A',
                'IsBudget' => 0,
                'IsDepreciation' => 0,
                'DepreciationRate' => '0.00',
            ],
        ]);
    }
}
